name: Code Quality

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # Weekly code quality check
    - cron: '0 9 * * 1'

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run linter
        run: npm run lint || true
        continue-on-error: true
      
      - name: Type check
        run: npm run type-check || true
        continue-on-error: true
      
      - name: Build test
        run: npm run build
      
      - name: Security audit
        run: npm audit --audit-level=high || true
        continue-on-error: true
      
      - name: Bundle size check
        run: |
          echo "📊 Bundle Size Report"
          echo "====================="
          du -sh .next/static/chunks/*.js | head -10 || true