name: Maintenance & Improvements

on:
  schedule:
    - cron: '0 9 * * 1' # Every Monday at 9 AM UTC
  workflow_dispatch:
    inputs:
      task:
        description: 'Maintenance task to run'
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - dependencies
          - issues
          - performance

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  # ===============================
  # 📦 Dependency Updates
  # ===============================
  dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    if: github.event.inputs.task == 'all' || github.event.inputs.task == 'dependencies'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: '20'
          cache: 'npm'

      - name: Check for updates
        id: updates
        run: |
          npm outdated --json > outdated.json || true
          if [ -s outdated.json ]; then
            echo "has_updates=true" >> $GITHUB_OUTPUT
          else
            echo "has_updates=false" >> $GITHUB_OUTPUT
          fi

      - name: Update dependencies
        if: steps.updates.outputs.has_updates == 'true'
        run: |
          npm update --save
          npm audit fix || true

      - name: Create Pull Request
        if: steps.updates.outputs.has_updates == 'true'
        uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f # v7.0.5
        with:
          title: 'chore: update dependencies'
          body: |
            ## 📦 Dependency Updates
            
            This PR updates project dependencies to their latest compatible versions.
            
            ### Changes
            - Updated npm dependencies
            - Fixed any security vulnerabilities
            
            Please review and test before merging.
          branch: deps/weekly-update
          commit-message: 'chore: update dependencies'

  # ===============================
  # 🎯 Issue Management
  # ===============================
  issues:
    name: Manage Issues
    runs-on: ubuntu-latest
    if: github.event.inputs.task == 'all' || github.event.inputs.task == 'issues'
    
    steps:
      - name: Close stale issues
        uses: actions/stale@28ca1036281a5e5922ead5184a1bbf96e5fc984e # v9.0.0
        with:
          stale-issue-message: 'This issue has been automatically marked as stale because it has not had recent activity.'
          close-issue-message: 'This issue has been closed due to inactivity.'
          days-before-stale: 30
          days-before-close: 7
          stale-issue-label: 'stale'

      - name: Add labels to new issues
        uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

  # ===============================
  # 📊 Performance Analysis
  # ===============================
  performance:
    name: Performance Check
    runs-on: ubuntu-latest
    if: github.event.inputs.task == 'all' || github.event.inputs.task == 'performance'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Analyze bundle size
        run: |
          echo "📊 Bundle Size Analysis"
          echo "========================"
          find .next -name "*.js" -type f -exec du -h {} + | sort -rh | head -20

      - name: Check for large dependencies
        run: |
          echo "📦 Large Dependencies"
          echo "===================="
          npx depcheck --json | jq '.dependencies' || echo "No unused dependencies found"

      - name: Create performance report
        if: always()
        run: |
          echo "## 📊 Performance Report" > performance-report.md
          echo "" >> performance-report.md
          echo "Generated on: $(date)" >> performance-report.md
          echo "" >> performance-report.md
          echo "### Bundle Analysis" >> performance-report.md
          echo "\`\`\`" >> performance-report.md
          find .next -name "*.js" -type f -exec du -h {} + | sort -rh | head -10 >> performance-report.md
          echo "\`\`\`" >> performance-report.md

      - name: Upload performance report
        if: always()
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: performance-report
          path: performance-report.md