name: Public Status Check

on:
  schedule:
    # Run once daily for public activity
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check App Status
        run: |
          echo "✅ FarDrops is operational"
          curl -s -o /dev/null -w "Response: %{http_code}\n" https://fardrops.xyz || true