name: Public Status Check

on:
  schedule:
    # Run once daily for public activity
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  health-check:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Check App Status
        run: |
          echo "✅ Checking FarDrops status..."
          response=$(curl -s -o /dev/null -w "%{http_code}" https://fardrops.xyz)
          if [ "$response" = "200" ]; then
            echo "✅ FarDrops is operational (HTTP $response)"
          else
            echo "⚠️ FarDrops returned HTTP $response"
            exit 1
          fi