name: Weekly Improvements

on:
  schedule:
    # Every Monday at 10 AM UTC
    - cron: '0 10 * * 1'
  workflow_dispatch:

jobs:
  create-improvement-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Create Weekly Improvement Issue
        uses: actions/github-script@v7
        with:
          script: |
            const date = new Date().toISOString().split('T')[0];
            const weekNumber = Math.ceil(((new Date() - new Date(new Date().getFullYear(), 0, 1)) / 86400000 + 1) / 7);
            
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `📈 Week ${weekNumber} Improvements Checklist`,
              body: `## Weekly Improvement Tasks - ${date}
              
              ### Performance
              - [ ] Review and optimize bundle size
              - [ ] Check Core Web Vitals scores
              - [ ] Update dependencies
              
              ### Features
              - [ ] Add one new airdrop detection method
              - [ ] Improve UI/UX based on any feedback
              - [ ] Enhance mobile experience
              
              ### Documentation
              - [ ] Update README if needed
              - [ ] Document any new features
              - [ ] Add code comments where needed
              
              ### Monitoring
              - [ ] Review detection accuracy
              - [ ] Check API performance
              - [ ] Verify all monitors working
              
              ### Growth
              - [ ] Share update on Farcaster
              - [ ] Engage with community
              - [ ] Track user metrics
              
              ---
              *This issue was automatically created to track weekly improvements*`,
              labels: ['enhancement', 'weekly-task']
            });
            
            console.log(`Created issue #${issue.data.number}`);
  
  lighthouse-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Lighthouse CI
        run: |
          npm install -g @lhci/cli
          lhci healthcheck || echo "Lighthouse check completed"